### ISSUE TITLE
Panda3d viewer is broken in examples

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/pinocchio#1189]
For more details see https://github.com/stack-of-tasks/pinocchio/pull/1183#pullrequestreview-402233989

**Comment by gabrielebndn** [comment]
The viewer isn't broken. The examples are broken. This is because they try to import `Panda3dViewer` (an alias of `Viewer`) and `ViewerClosedError` from `pinocchio.visualize.panda3d_visualize`, but they are not there any more. I think the changes in #1183 were correct and the solution to fix the examples is simple: just import `Viewer` and `ViewerClosedError` directly from `panda3d_viewer`.

**Comment by cmastalli** [comment]
Thanks for the clarification. Indeed, I wasn't sure about this point.

**Comment by ikalevatykh** [comment]
@cmastalli , it is not a good idea to "fix" working code ;)

**Comment by cmastalli** [comment]
@cmastalli , it is not a good idea to "fix" working code ;)

@ikalevatykh I didn't modify that part of code. I just fixed the installation of the files. You could check the for history for details.

**Comment by jcarpent** [comment]
Solved by #1191.
